### ISSUE TITLE
Link to "Line" not "Note"

### ISSUE THREAD

**Issue by tedblizzard** [ryanjamurphy/workbench-obsidian#1]
Wonderful idea and thank you for your work on this.
One improvement when we "Link to Line" the TEXT in the workbench should be the LINE text, not the NOTE text.  Note text is not helpful.  See attached.  Thank you, Ted

![image](https://user-images.githubusercontent.com/2208182/98769751-33fb0700-2413-11eb-8292-5c9347f4d7cb.png)

**Comment by ryanjamurphy** [comment]
Hey, Ted, thanks! This is a function of Obsidian's block referencing. If you switch to Previewing the note, it will show an embed of those last two lines, so you'll see the text you're hoping for.

The plugin also already has a "copy line" command, and you can customize cmd/win+alt+click to copy line in the settings.

Nonetheless it might be possible to copy line content and put it into a link format, like this: `[some sentence](some note title#^blockid)`. I'll look into it!

**Comment by tedblizzard** [comment]
WOW! this is extremely useful.  Thank you for all your work on this.  The Workbench is not my base in Obsidian.
I look forward to your updates.

**Comment by ryanjamurphy** [comment]
Just following up (and tracking my own thinking on this). We could use the idea I described above to gain both content and links in preview and edit mode—however, the links would have to be percent-encoded, so instead of `[some sentence](some note title#^blockid)` it would look like `[some sentence](some%20note%20title#^blockid)`. In edit mode only (this wouldn't influence the title—the note would still be "Some note title"). Interesting!

**Comment by ryanjamurphy** [comment]
I've implemented the above. You can now copy the current line as a markdown-formatted link to its block, in case you don't want to use transclusion (aka embedding) for some reason.
